### ISSUE TITLE
Defunct link now serving malware

### ISSUE THREAD

**Issue by jeremygaither** [francoiswnel/Monokai-Dark-Soda-for-JetBrains#1]
The link for Eclectide's Monokai Theme for IntelliJ (`http--eclectide-dot-com/blog/2014/11/23/monokai-theme-intellij/`) is now serving random adware and sometimes malware. The first page replaces the location with JavaScript with a unique meh. The second serves a random 302 redirect, also with a unique key. The payload seems to differ based on user agent, and some show up as malware on [VirusTotal](https://www.virustotal.com/gui/home/url).

**Comment by jeremygaither** [comment]
@francoiswnel  Tagging just in case you're not monitoring for PRs...

**Comment by francoiswnel** [comment]
@jeremygaither Thanks for letting me know! I've removed the link.
